import { DefaultLayout } from '@/app/layouts'
import Head from 'next/head'
import { Catalog } from '@/components'


const CatalogPage = () => {
  return (
    <>
      <Head>
        <title>Personal</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Catalog />
    </>
  )
}

CatalogPage.getLayout = function getLayout(page) {
  return <DefaultLayout>{page}</DefaultLayout>
}

export default CatalogPage

