import Head from 'next/head'
import '@/styles/home.scss'
import { Tangerine } from 'next/font/google'

const font = Tangerine({ subsets: ['latin'], weight: '400' })

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='main'>
        <h1 className={`title-main ${font.className}`}>Lichi</h1>
      </main>
    </>
  )
}

export default Home
